sudo: required

language: javascript

services: 
  - docker

before_install: 
  - docker build -t johnny25580/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true johnny25580/docker-react-app npm run test

deploy:
  on:
    branch: main
